try to do button html test
khospodarysko/training-selenium pull request #1
Opened 2018-01-29 18:46 UTC by ahospodarysko

2018-01-30 10:42 UTC, kostia-hospodarysko requested changes

2018-01-30 10:42 UTC, kostia-hospodarysko commented on src/test/java/com/khospodarysko/ButtonTest.java
> +            wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.hide")));
Look inside how `elementToBeClickable` is implemented. Next step is to how to implement your own `ExpectedCondition`, let's say `clickElementUntilText()` - it should click on element until its text becomes "Clicked 5" (think of what it has to accept as parameter).
Has to be `wait.until(MyEC.clickElementUntilText(By.cssSelector("button.hide")), "Clicked 5");`.
Use the same approach as in `elementToBeClickable`.

2018-01-30 10:42 UTC, kostia-hospodarysko commented on src/test/java/com/khospodarysko/ButtonTest.java
> +            button.click();
It is enough to click 5 times and to assert, as while already kind of assert the text, no need `while` here.

2018-02-06 18:34 UTC, ahospodarysko commented on src/test/java/com/khospodarysko/ButtonTest.java
> +            wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.hide")));
I have to create my own class like - MyExpectedCondition - and write my own method - clickElementUntilText(), this method will be waiting if button with text - Delayed Button - is displayed on the page?

2018-02-06 18:36 UTC, ahospodarysko commented on src/test/java/com/khospodarysko/ButtonTest.java
> +            button.click();
And here i just click five times - button.click(), button.click() .... and assert if button has clicked?

2018-02-06 19:24 UTC, ahospodarysko commented on src/test/java/com/khospodarysko/ButtonTest.java
> +            wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button.hide")));
I cant understand why i need this method - clickElementUntilText() - cause i just wait for button and then click five times and assert if button have text - "Clicked 5". In selenium we already have method - visibilityOfElementWithText

2018-02-06 19:27 UTC, merged